### ISSUE TITLE
Python version not 3.7 or greater

### ISSUE THREAD

**Issue by hesmithh** [Martini-Force-Field-Initiative/OLIVES#1]
Hello,

The readme says OLIVES is compatible with python3.7 or greater, but I get an ImportError with 3.9:
> ImportError: cannot import name 'gcd' from 'fractions' 

According to [this discussion](https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions), seems like fractions.gcd does not exist in 3.9+.

By the way, the paper is very nice and the idea is exciting! Looking forward to trying it. Thanks for sharing the code.

**Comment by KasperBuskPedersen** [comment]
Hi @yummy-hat 

Indeed my python is 3.7. 
This seems to be an issue of networkx version with python 3.9 or greater. 
https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions

Could you try to install networkx">=2.5" ? Let me know if that solves the issue and I will update the readme accordingly. 

Hope the model will be useful to you :)

Best
Kasper

**Comment by hesmithh** [comment]
Yes, networkx>=2.5 worked for me with python 3.7. Thanks!
